### ISSUE TITLE
React 16 roadmap

### ISSUE THREAD

**Issue by Deraen** [cljsjs/packages#1170]
- [x] Package create-react-class
- [x] Remove react-with-addons
- [ ] Mirror npm packaging, react + react-dom, -> include react-dom/server in react-dom package
- [x] Package https://github.com/reactjs/react-transition-group
- [ ] Package https://github.com/kolodny/immutability-helper
- [ ] React-dom/test-utils https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#react-test-utils

**Comment by anmonteiro** [comment]
Just opened #1171 to add react-transition-group

**Comment by Deraen** [comment]
Latest beta is packaged and I think all the additional packages we can package, are done.
